### ISSUE TITLE
Creation of Base Build Script Box stops when running Vagrant Up

### ISSUE THREAD

**Issue by gttechlife** [scotch-io/scotch-box-build-scripts#2]
When running through the default build on vagrant up, the box completely freezes up provisioning and will not continue. No matter how long I wait it just sits there stuck at this one part. See Screenshot Attached.

FYI: I paid for both a single user and Unlimited User Liscence.

![image](https://user-images.githubusercontent.com/22176876/28271922-fdc698d6-6ad7-11e7-954e-280f097a7939.png)

**Comment by gttechlife** [comment]
Well this odd. Second time this has happened. When using Ctrl+C to stop the process, it changes the language of my git terminal.

![image](https://user-images.githubusercontent.com/22176876/28272379-5198a9c6-6ad9-11e7-976a-eb6109dd67e7.png)

**Comment by grahamtk** [comment]
Same issue here. 
The issue is described here: Hi!
I meet this issue with the non-interactive build script being halted by the interactive setup dialogue for grub:
As described here:
https://www.bountysource.com/issues/37968311-ubuntu-grub-pc-forces-non-interactive-apt-get-upgrade

Also seems nginx does not start. Ill create a new issue if the grub issue does not resove that.

Can I get some help on how to proceed with this?
Best regards,
Øyvind.

**Comment by smidgedy** [comment]
Same issue here this morning - I found a nice explanation of why it happens [here](https://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt) and got around it with basically the same fix as @grahamtk but in a single liner, changing

```
sudo apt-get -q -y upgrade
```

to:

```
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
```
